language: java
sudo: false
install: true

jdk:
  - oraclejdk8

rvm:
  - 2.2

before_script:
  - gem install awesome_bot

script:
  - awesome_bot README.md --allow-dupe --allow-redirect --white-list $wl
  - mvn clean install
  
cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
